{% set name = "tangods-aerotechensemble" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - libtool
    - pkg-config
  host:
    - cppzmq
    - cpptango <9.4
    - omniorb
    - omniorb-libs
    - yat
    - yat4tango

test:
  commands:
    - AerotechEnsembleDS --help 2>&1 | grep usage

about:
  home: https://gitlab.maxiv.lu.se/kits-maxiv/dev-soleil-aerotechensemble
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tango Device for Aerotech Ensemble
